Add `makoctl set`
Closes: https://github.com/emersion/mako/issues/138

diff --git a/makoctl b/makoctl
--- a/makoctl
+++ b/makoctl
@@ -12,12 +12,13 @@ usage() {
 	echo "                           notification action to be invoked"
 	echo "  list                     List notifications"
 	echo "  reload                   Reload the configuration file"
+	echo "  set <key>=<value>        Set a global configuration option"
 	echo "  help                     Show this help"
 }
 
 call() {
 	busctl -j --user call org.freedesktop.Notifications /fr/emersion/Mako \
-		fr.emersion.Mako "$@"
+		fr.emersion.Mako -- "$@"
 }
 
 if [ $# -eq 0 ] || [ $# -gt 5 ]; then
@@ -80,6 +81,19 @@ case "$1" in
 	;;
 "reload")
 	call Reload
+	;;
+"set")
+	if [ $# -lt 2 ]; then
+		echo >&2 "makoctl: missing argument for 'set'"
+		exit 1
+	fi
+	name="${2%%'='*}"
+	value="${2#*'='}"
+	if [ "$2" = "$name" ]; then
+		echo >&2 "makoctl: missing '=' in argument for 'set'"
+		exit 1
+	fi
+	call SetConfigOption "ss" "$name" "$value"
 	;;
 "help"|"--help"|"-h")
 	usage
